puts("My age in years is")
puts(30)
puts("My age in months is")
puts(30 * 12)
puts("My age in days is")
puts(30 * 365)
age = 50
puts("My age in years is")
puts(age)
puts("My age in months is")
puts(age * 12)
puts("My age in days is")
puts(age * 365)
age = 21
puts("My age in years is") 
puts(age)
puts("My age in months is")
puts(age * 12)
puts("My age in days is")
puts(age * 365)
age = gets().chomp().to_i()
puts("My age in years is")
puts(age)
puts("My age in months is")
puts(age * 12)
puts("My age in days is")
puts(age * 365)
age = gets().chomp().to_i()
puts("Your age in years is")
puts(age)
puts("Your age in months is")
puts(age * 12)
puts("Your age in days is")
puts(age * 365)