puts("What's your number 1 favorite movie?")
movie_1 = gets().chomp()
puts("What's your second favorite movie?")
movie_2 = gets().chomp()
puts("What's your third favorite movie?")
movie_3 = gets().chomp()
puts("What's your fourth favorite movie?")
movie_4 = gets().chomp()
puts("What's your fifth favorite movie?")
movie_5 = gets().chomp()
puts("What's your sixth favorite movie?")
movie_6 = gets().chomp()
puts("What's your seventh favorite movie?")
movie_7 = gets().chomp()
puts("What's your eighth favorite movie?")
movie_8 = gets().chomp()
puts("What's your ninth favorite movie?")
movie_9 = gets().chomp()
puts("What's your tenth favorite movie?")
movie_10 = gets().chomp()
puts("Far out!")
puts("You're number 1 favorite movie is " + movie_1)
puts("You're second favorite movie is " + movie_2)
puts("You're third favorite movie is " + movie_3)
puts("You're fourth favorite movie is " + movie_4)
puts("You're fifth favorite movie is " + movie_5)
puts("You're sixth favorite movie is " + movie_6)
puts("You're seventh favorite movie is " + movie_7)
puts("You're eighth favorite movie is " + movie_8)
puts("You're ninth favorite movie is " + movie_9)
puts("You're tenth favorite movie is " + movie_10)
puts("You have great taste in movies!")